<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('words')->insert([
            ['word' => '爱', 'pinyin' => 'ài', 'meaning' => 'to love', 'example_sentence' => '我爱你。'],
            ['word' => '八', 'pinyin' => 'bā', 'meaning' => 'eight', 'example_sentence' => '今天是八月八号。'],
            ['word' => '爸爸', 'pinyin' => 'bàba', 'meaning' => 'father', 'example_sentence' => '我爸爸是医生。'],
            ['word' => '杯子', 'pinyin' => 'bēizi', 'meaning' => 'cup', 'example_sentence' => '这个杯子是我的。'],
            ['word' => '北京', 'pinyin' => 'Běijīng', 'meaning' => 'Beijing', 'example_sentence' => '北京是中国的首都。'],
            ['word' => '本', 'pinyin' => 'běn', 'meaning' => 'measure word for books', 'example_sentence' => '我有一本书。'],
            ['word' => '不', 'pinyin' => 'bù', 'meaning' => 'not', 'example_sentence' => '我不喜欢吃辣。'],
            ['word' => '不客气', 'pinyin' => 'bú kèqi', 'meaning' => 'you’re welcome', 'example_sentence' => '谢谢你！不客气。'],
            ['word' => '菜', 'pinyin' => 'cài', 'meaning' => 'dish, vegetable', 'example_sentence' => '这道菜很好吃。'],
            ['word' => '茶', 'pinyin' => 'chá', 'meaning' => 'tea', 'example_sentence' => '我喜欢喝茶。'],
            ['word' => '吃', 'pinyin' => 'chī', 'meaning' => 'to eat', 'example_sentence' => '我吃苹果。'],
            ['word' => '出租车', 'pinyin' => 'chūzūchē', 'meaning' => 'taxi', 'example_sentence' => '我坐出租车去机场。'],
            ['word' => '打电话', 'pinyin' => 'dǎ diànhuà', 'meaning' => 'to make a phone call', 'example_sentence' => '我给妈妈打电话。'],
            ['word' => '大', 'pinyin' => 'dà', 'meaning' => 'big', 'example_sentence' => '这只狗很大。'],
            ['word' => '的', 'pinyin' => 'de', 'meaning' => 'possessive particle', 'example_sentence' => '这是我的书。'],
            ['word' => '点', 'pinyin' => 'diǎn', 'meaning' => 'o’clock', 'example_sentence' => '现在是三点。'],
            ['word' => '电脑', 'pinyin' => 'diànnǎo', 'meaning' => 'computer', 'example_sentence' => '我用电脑工作。'],
            ['word' => '电视', 'pinyin' => 'diànshì', 'meaning' => 'television', 'example_sentence' => '我喜欢看电视。'],
            ['word' => '电影', 'pinyin' => 'diànyǐng', 'meaning' => 'movie', 'example_sentence' => '这部电影很好看。'],
            ['word' => '东西', 'pinyin' => 'dōngxi', 'meaning' => 'thing', 'example_sentence' => '我买了一些东西。'],
            ['word' => '都', 'pinyin' => 'dōu', 'meaning' => 'all', 'example_sentence' => '我们都去看电影。'],
            ['word' => '读', 'pinyin' => 'dú', 'meaning' => 'to read', 'example_sentence' => '我喜欢读书。'],
            ['word' => '对不起', 'pinyin' => 'duìbuqǐ', 'meaning' => 'sorry', 'example_sentence' => '对不起，我迟到了。'],
            ['word' => '多', 'pinyin' => 'duō', 'meaning' => 'many, much', 'example_sentence' => '这里有很多人。'],
            ['word' => '多少', 'pinyin' => 'duōshao', 'meaning' => 'how many, how much', 'example_sentence' => '这个多少钱？'],
            ['word' => '儿子', 'pinyin' => 'érzi', 'meaning' => 'son', 'example_sentence' => '我儿子五岁了。'],
            ['word' => '二', 'pinyin' => 'èr', 'meaning' => 'two', 'example_sentence' => '我有两个苹果。'],
            ['word' => '饭馆', 'pinyin' => 'fànguǎn', 'meaning' => 'restaurant', 'example_sentence' => '这家饭馆的菜很好吃。'],
            ['word' => '飞机', 'pinyin' => 'fēijī', 'meaning' => 'airplane', 'example_sentence' => '我坐飞机去北京。'],
            ['word' => '分钟', 'pinyin' => 'fēnzhōng', 'meaning' => 'minute', 'example_sentence' => '我等了五分钟。'],
            ['word' => '高兴', 'pinyin' => 'gāoxìng', 'meaning' => 'happy', 'example_sentence' => '我很高兴认识你。'],
            ['word' => '个', 'pinyin' => 'gè', 'meaning' => 'measure word', 'example_sentence' => '我有一个苹果。'],
            ['word' => '工作', 'pinyin' => 'gōngzuò', 'meaning' => 'work', 'example_sentence' => '我的工作是老师。'],
            ['word' => '狗', 'pinyin' => 'gǒu', 'meaning' => 'dog', 'example_sentence' => '我有一只狗。'],
            ['word' => '汉语', 'pinyin' => 'Hànyǔ', 'meaning' => 'Chinese language', 'example_sentence' => '我在学汉语。'],
            ['word' => '好', 'pinyin' => 'hǎo', 'meaning' => 'good', 'example_sentence' => '今天天气很好。'],
            ['word' => '号', 'pinyin' => 'hào', 'meaning' => 'date, number', 'example_sentence' => '今天是几号？'],
            ['word' => '喝', 'pinyin' => 'hē', 'meaning' => 'to drink', 'example_sentence' => '我喝水。'],
            ['word' => '和', 'pinyin' => 'hé', 'meaning' => 'and', 'example_sentence' => '我和他是同学。'],
            ['word' => '很', 'pinyin' => 'hěn', 'meaning' => 'very', 'example_sentence' => '我很高兴。'],
            ['word' => '后面', 'pinyin' => 'hòumian', 'meaning' => 'behind', 'example_sentence' => '他在我后面。'],
            ['word' => '回', 'pinyin' => 'huí', 'meaning' => 'to return', 'example_sentence' => '我回家了。'],
            ['word' => '会', 'pinyin' => 'huì', 'meaning' => 'can, to be able to', 'example_sentence' => '我会说汉语。'],
            ['word' => '几', 'pinyin' => 'jǐ', 'meaning' => 'how many', 'example_sentence' => '你有几个苹果？'],
            ['word' => '家', 'pinyin' => 'jiā', 'meaning' => 'home, family', 'example_sentence' => '我家在北京。'],
            ['word' => '叫', 'pinyin' => 'jiào', 'meaning' => 'to be called', 'example_sentence' => '我叫李华。'],
            ['word' => '今天', 'pinyin' => 'jīntiān', 'meaning' => 'today', 'example_sentence' => '今天是星期一。'],
            ['word' => '九', 'pinyin' => 'jiǔ', 'meaning' => 'nine', 'example_sentence' => '今天是九月九号。'],
            ['word' => '开', 'pinyin' => 'kāi', 'meaning' => 'to open, to drive', 'example_sentence' => '我开车去上班。'],
            ['word' => '看', 'pinyin' => 'kàn', 'meaning' => 'to look, to see', 'example_sentence' => '我看电视。'],
            ['word' => '看见', 'pinyin' => 'kànjiàn', 'meaning' => 'to see', 'example_sentence' => '我看见他了。'],
            ['word' => '块', 'pinyin' => 'kuài', 'meaning' => 'measure word for money', 'example_sentence' => '这个多少钱一块？'],
            ['word' => '来', 'pinyin' => 'lái', 'meaning' => 'to come', 'example_sentence' => '请进来。'],
            ['word' => '老师', 'pinyin' => 'lǎoshī', 'meaning' => 'teacher', 'example_sentence' => '他是我的老师。'],
            ['word' => '了', 'pinyin' => 'le', 'meaning' => 'completed action marker', 'example_sentence' => '我吃饭了。'],
            ['word' => '冷', 'pinyin' => 'lěng', 'meaning' => 'cold', 'example_sentence' => '今天很冷。'],
            ['word' => '里', 'pinyin' => 'lǐ', 'meaning' => 'inside', 'example_sentence' => '我在家里。'],
            ['word' => '六', 'pinyin' => 'liù', 'meaning' => 'six', 'example_sentence' => '今天是六月六号。'],
            ['word' => '妈妈', 'pinyin' => 'māma', 'meaning' => 'mother', 'example_sentence' => '我妈妈很漂亮。'],
            ['word' => '吗', 'pinyin' => 'ma', 'meaning' => 'question particle', 'example_sentence' => '你好吗？'],
            ['word' => '买', 'pinyin' => 'mǎi', 'meaning' => 'to buy', 'example_sentence' => '我买了一个苹果。'],
            ['word' => '猫', 'pinyin' => 'māo', 'meaning' => 'cat', 'example_sentence' => '我有一只猫。'],
            ['word' => '没', 'pinyin' => 'méi', 'meaning' => 'not have', 'example_sentence' => '我没有钱。'],
            ['word' => '没关系', 'pinyin' => 'méi guānxi', 'meaning' => 'it doesn’t matter', 'example_sentence' => '对不起。没关系。'],
            ['word' => '米饭', 'pinyin' => 'mǐfàn', 'meaning' => 'cooked rice', 'example_sentence' => '我喜欢吃米饭。'],
            ['word' => '明天', 'pinyin' => 'míngtiān', 'meaning' => 'tomorrow', 'example_sentence' => '明天是星期二。'],
            ['word' => '名字', 'pinyin' => 'míngzi', 'meaning' => 'name', 'example_sentence' => '我的名字叫李华。'],
            ['word' => '哪', 'pinyin' => 'nǎ', 'meaning' => 'which', 'example_sentence' => '你是哪国人？'],
            ['word' => '哪儿', 'pinyin' => 'nǎr', 'meaning' => 'where', 'example_sentence' => '你在哪儿？'],
            ['word' => '那', 'pinyin' => 'nà', 'meaning' => 'that', 'example_sentence' => '那是我的书。'],
            ['word' => '呢', 'pinyin' => 'ne', 'meaning' => 'question particle', 'example_sentence' => '你呢？'],
            ['word' => '能', 'pinyin' => 'néng', 'meaning' => 'can, to be able to', 'example_sentence' => '我能说汉语。'],
            ['word' => '你', 'pinyin' => 'nǐ', 'meaning' => 'you', 'example_sentence' => '你好吗？'],
            ['word' => '年', 'pinyin' => 'nián', 'meaning' => 'year', 'example_sentence' => '今年是2024年。'],
            ['word' => '女儿', 'pinyin' => 'nǚ’ér', 'meaning' => 'daughter', 'example_sentence' => '我女儿三岁了。'],
            ['word' => '朋友', 'pinyin' => 'péngyou', 'meaning' => 'friend', 'example_sentence' => '他是我的朋友。'],
            ['word' => '漂亮', 'pinyin' => 'piàoliang', 'meaning' => 'beautiful', 'example_sentence' => '这朵花很漂亮。'],
            ['word' => '苹果', 'pinyin' => 'píngguǒ', 'meaning' => 'apple', 'example_sentence' => '我喜欢吃苹果。'],
            ['word' => '七', 'pinyin' => 'qī', 'meaning' => 'seven', 'example_sentence' => '今天是七月七号。'],
            ['word' => '前面', 'pinyin' => 'qiánmian', 'meaning' => 'in front', 'example_sentence' => '他在我前面。'],
            ['word' => '钱', 'pinyin' => 'qián', 'meaning' => 'money', 'example_sentence' => '我有很多钱。'],
            ['word' => '请', 'pinyin' => 'qǐng', 'meaning' => 'please', 'example_sentence' => '请进。'],
            ['word' => '去', 'pinyin' => 'qù', 'meaning' => 'to go', 'example_sentence' => '我去学校。'],
            ['word' => '热', 'pinyin' => 'rè', 'meaning' => 'hot', 'example_sentence' => '今天很热。'],
            ['word' => '人', 'pinyin' => 'rén', 'meaning' => 'person', 'example_sentence' => '我是中国人。'],
            ['word' => '认识', 'pinyin' => 'rènshi', 'meaning' => 'to know', 'example_sentence' => '我认识他。'],
            ['word' => '三', 'pinyin' => 'sān', 'meaning' => 'three', 'example_sentence' => '今天是三月三号。'],
            ['word' => '商店', 'pinyin' => 'shāngdiàn', 'meaning' => 'shop', 'example_sentence' => '我去商店买东西。'],
            ['word' => '上', 'pinyin' => 'shàng', 'meaning' => 'on, up', 'example_sentence' => '书在桌子上。'],
            ['word' => '上午', 'pinyin' => 'shàngwǔ', 'meaning' => 'morning', 'example_sentence' => '我上午去上班。'],
            ['word' => '少', 'pinyin' => 'shǎo', 'meaning' => 'few, little', 'example_sentence' => '这里人很少。'],
            ['word' => '谁', 'pinyin' => 'shéi', 'meaning' => 'who', 'example_sentence' => '他是谁？'],
            ['word' => '什么', 'pinyin' => 'shénme', 'meaning' => 'what', 'example_sentence' => '你在做什么？'],
            ['word' => '十', 'pinyin' => 'shí', 'meaning' => 'ten', 'example_sentence' => '今天是十月十号。'],
            ['word' => '时候', 'pinyin' => 'shíhou', 'meaning' => 'time', 'example_sentence' => '什么时候见面？'],
            ['word' => '是', 'pinyin' => 'shì', 'meaning' => 'to be', 'example_sentence' => '我是学生。'],
            ['word' => '书', 'pinyin' => 'shū', 'meaning' => 'book', 'example_sentence' => '我喜欢看书。'],
            ['word' => '水', 'pinyin' => 'shuǐ', 'meaning' => 'water', 'example_sentence' => '我喝水。'],
            ['word' => '水果', 'pinyin' => 'shuǐguǒ', 'meaning' => 'fruit', 'example_sentence' => '我喜欢吃水果。'],
            ['word' => '睡觉', 'pinyin' => 'shuìjiào', 'meaning' => 'to sleep', 'example_sentence' => '我想睡觉。'],
            ['word' => '说', 'pinyin' => 'shuō', 'meaning' => 'to speak, to say', 'example_sentence' => '他说汉语。'],
            ['word' => '四', 'pinyin' => 'sì', 'meaning' => 'four', 'example_sentence' => '今天是四月四号。'],
            ['word' => '岁', 'pinyin' => 'suì', 'meaning' => 'year of age', 'example_sentence' => '我二十岁。'],
            ['word' => '他', 'pinyin' => 'tā', 'meaning' => 'he', 'example_sentence' => '他是医生。'],
            ['word' => '她', 'pinyin' => 'tā', 'meaning' => 'she', 'example_sentence' => '她是老师。'],
            ['word' => '太', 'pinyin' => 'tài', 'meaning' => 'too, very', 'example_sentence' => '太好了！'],
            ['word' => '天气', 'pinyin' => 'tiānqì', 'meaning' => 'weather', 'example_sentence' => '今天天气很好。'],
            ['word' => '听', 'pinyin' => 'tīng', 'meaning' => 'to listen', 'example_sentence' => '我喜欢听音乐。'],
            ['word' => '同学', 'pinyin' => 'tóngxué', 'meaning' => 'classmate', 'example_sentence' => '他是我的同学。'],
            ['word' => '喂', 'pinyin' => 'wèi', 'meaning' => 'hello (on the phone)', 'example_sentence' => '喂，你好！'],
            ['word' => '我', 'pinyin' => 'wǒ', 'meaning' => 'I, me', 'example_sentence' => '我是学生。'],
            ['word' => '我们', 'pinyin' => 'wǒmen', 'meaning' => 'we, us', 'example_sentence' => '我们都是学生。'],
            ['word' => '五', 'pinyin' => 'wǔ', 'meaning' => 'five', 'example_sentence' => '今天是五月五号。'],
            ['word' => '喜欢', 'pinyin' => 'xǐhuan', 'meaning' => 'to like', 'example_sentence' => '我喜欢看电影。'],
            ['word' => '下', 'pinyin' => 'xià', 'meaning' => 'under, down', 'example_sentence' => '书在桌子下。'],
            ['word' => '下午', 'pinyin' => 'xiàwǔ', 'meaning' => 'afternoon', 'example_sentence' => '我下午去上班。'],
            ['word' => '下雨', 'pinyin' => 'xiàyǔ', 'meaning' => 'to rain', 'example_sentence' => '今天下雨了。'],
            ['word' => '先生', 'pinyin' => 'xiānsheng', 'meaning' => 'Mr., husband', 'example_sentence' => '王先生是医生。'],
            ['word' => '现在', 'pinyin' => 'xiànzài', 'meaning' => 'now', 'example_sentence' => '现在是三点。'],
            ['word' => '想', 'pinyin' => 'xiǎng', 'meaning' => 'to think, to want', 'example_sentence' => '我想吃苹果。'],
            ['word' => '小', 'pinyin' => 'xiǎo', 'meaning' => 'small', 'example_sentence' => '这只狗很小。'],
            ['word' => '小姐', 'pinyin' => 'xiǎojiě', 'meaning' => 'Miss, young lady', 'example_sentence' => '王小姐是老师。'],
            ['word' => '些', 'pinyin' => 'xiē', 'meaning' => 'some', 'example_sentence' => '这些苹果很甜。'],
            ['word' => '写', 'pinyin' => 'xiě', 'meaning' => 'to write', 'example_sentence' => '我喜欢写字。'],
            ['word' => '谢谢', 'pinyin' => 'xièxie', 'meaning' => 'thank you', 'example_sentence' => '谢谢你！'],
            ['word' => '星期', 'pinyin' => 'xīngqī', 'meaning' => 'week', 'example_sentence' => '今天是星期五。'],
            ['word' => '学生', 'pinyin' => 'xuésheng', 'meaning' => 'student', 'example_sentence' => '我是学生。'],
            ['word' => '学习', 'pinyin' => 'xuéxí', 'meaning' => 'to study', 'example_sentence' => '我在学习汉语。'],
            ['word' => '学校', 'pinyin' => 'xuéxiào', 'meaning' => 'school', 'example_sentence' => '我去学校。'],
            ['word' => '一', 'pinyin' => 'yī', 'meaning' => 'one', 'example_sentence' => '我有一个苹果。'],
            ['word' => '衣服', 'pinyin' => 'yīfu', 'meaning' => 'clothes', 'example_sentence' => '这件衣服很好看。'],
            ['word' => '医生', 'pinyin' => 'yīshēng', 'meaning' => 'doctor', 'example_sentence' => '我是医生。'],
            ['word' => '医院', 'pinyin' => 'yīyuàn', 'meaning' => 'hospital', 'example_sentence' => '我去医院看病。'],
            ['word' => '椅子', 'pinyin' => 'yǐzi', 'meaning' => 'chair', 'example_sentence' => '请坐在椅子上。'],
            ['word' => '有', 'pinyin' => 'yǒu', 'meaning' => 'to have', 'example_sentence' => '我有很多朋友。'],
            ['word' => '月', 'pinyin' => 'yuè', 'meaning' => 'month', 'example_sentence' => '今天是几月几号？'],
            ['word' => '在', 'pinyin' => 'zài', 'meaning' => 'at, in, on', 'example_sentence' => '我在家。'],
            ['word' => '再见', 'pinyin' => 'zàijiàn', 'meaning' => 'goodbye', 'example_sentence' => '再见！明天见。'],
            ['word' => '怎么', 'pinyin' => 'zěnme', 'meaning' => 'how', 'example_sentence' => '你怎么去学校？'],
            ['word' => '怎么样', 'pinyin' => 'zěnmeyàng', 'meaning' => 'how about', 'example_sentence' => '你今天怎么样？'],
            ['word' => '这', 'pinyin' => 'zhè', 'meaning' => 'this', 'example_sentence' => '这是我的书。'],
            ['word' => '中国', 'pinyin' => 'Zhōngguó', 'meaning' => 'China', 'example_sentence' => '我住在中国。'],
            ['word' => '中午', 'pinyin' => 'zhōngwǔ', 'meaning' => 'noon', 'example_sentence' => '我们中午见面。'],
            ['word' => '住', 'pinyin' => 'zhù', 'meaning' => 'to live', 'example_sentence' => '我住在北京。'],
            ['word' => '桌子', 'pinyin' => 'zhuōzi', 'meaning' => 'table', 'example_sentence' => '书在桌子上。'],
            ['word' => '字', 'pinyin' => 'zì', 'meaning' => 'character', 'example_sentence' => '我会写很多汉字。'],
            ['word' => '昨天', 'pinyin' => 'zuótiān', 'meaning' => 'yesterday', 'example_sentence' => '昨天我去看电影了。'],
            ['word' => '坐', 'pinyin' => 'zuò', 'meaning' => 'to sit', 'example_sentence' => '请坐。'],
            ['word' => '做', 'pinyin' => 'zuò', 'meaning' => 'to do', 'example_sentence' => '我在做作业。']
        ]);        
    }
}
